version: '2'
services:
  server-lb:
    build: .
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '4000:4000'
    links:
      - user-ms-1
      - user-ms-2

  user-ms-1:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '5984'
      DB_URL: 'users-db'
      HOST_PORT: '4001'
    ports:
      - '4001:4001'
    links:
      - users-db

  user-ms-2:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '5984'
      DB_URL: 'users-db'
      HOST_PORT: '4002'
    ports:
      - '4002:4002'
    links:
      - users-db

  users-db:
    image: klaemo/couchdb:2.0-single
    restart: always
    logging:
      driver: 'none'
    ports:
      - '3000:5984'